### ISSUE TITLE
7.1.2 released

### ISSUE THREAD

**Issue by Demon000** [AOSP-CAF/platform_manifest#5]
Tag: LA.UM.5.8.r1-01300-8x98.0

https://wiki.codeaurora.org/xwiki/bin/QAEP/release

**Comment by Meninblack007** [comment]
Yeah. I know. Thanks :p

**Comment by boswelja** [comment]
How do you guys know when there's a new CAF tag?

**Comment by Demon000** [comment]
@boswelja I just check that link from time to time.

**Comment by TechExhibeo** [comment]
issue attended 😛

**Comment by crian** [comment]
How can I build n-mr2 with this manifest?

**Comment by Meninblack007** [comment]
Manifest will be up on github in a day or two :)

**Comment by crian** [comment]
@Meninblack007 thanks. Would like to build AOSP-CAF for the Nextbit Robin.

**Comment by Meninblack007** [comment]
Cool :D

**Comment by dev-harsh1998** [comment]
waiting @Meninblack007 ...

**Comment by boswelja** [comment]
@dev-harsh1998 Keep waiting.. @Meninblack007 will release when he feels it is nessecary

**Comment by Meninblack007** [comment]
Manifest up :)
